### ISSUE TITLE
Genres doesn't return genres for most artists

### ISSUE THREAD

**Issue by singhprd** [guilhermesad/rspotify#79]
Genres doesn't return genres for most artists. 
I have taken the example of Arctic Monkeys in the docs and printed to the terminal and genres doesn't seem to return correctly. 
Popularity, top tracks ect all work correctly. Maybe Spotify have changed the way they handle genres?
('Bruce Springsteen' still returns "[roots rock, singer-songwriter]")

require 'rspotify'

artists = RSpotify::Artist.search('Arctic Monkeys')

arctic_monkeys = artists.first
arctic_monkeys.popularity      #=> 74
puts arctic_monkeys.genres    

--Returns nil --

**Comment by guilhermesad** [comment]
If you hit the API directly you'll see `genres` field is still there, and it gets populated depending on the artist. Take for example https://api.spotify.com/v1/search?q=Cher&type=artist

Maybe just the Arctic Monkeys genres data in Spotify got lost. @JMPerez would you know about that? Looks like a Spotify issue rather than the wrapper's.

**Comment by JMPerez** [comment]
@guilhermesad You are right. The wrapper is making the request properly, it's the Web API that doesn't return genres for some artists. There is a similar problem with albums (see https://github.com/spotify/web-api/issues/157). Not sure if this will be fixed in the near future.

**Comment by guilhermesad** [comment]
Thanks for clarifying @JMPerez. Closing this then as it's not a RSpotify issue.

**Comment by singhprd** [comment]
thanks for having a look. And thumbs up for a great gem!

**Comment by guilhermesad** [comment]
thanks you! :)
